### ISSUE TITLE
Solid router does not work on wails

### ISSUE THREAD

**Issue by renatonmag** [xijaja/wails-template-solid-ts#1]
Hey mate!

Do you know how to make the solid router to work??

Thks!

**Comment by xijaja** [comment]
Maybe you should read the solid router documentation：https://github.com/solidjs/solid-router
wails-template-solid-ts also uses it。

**Comment by xijaja** [comment]
Maybe solid-router got an update, I'll try it later.

**Comment by xijaja** [comment]
@renatonmag Maybe you should try this repository of mine: https://github.com/xijaja/wails-template-solid-tailwindcss
